config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    resources :posts do
      resources :comments
  end

  root "pages#about"

  get "/about", to: 'pages#about'

  get "/me" => "pages#me"

  get "/contact" => "pages#contactMe"

  post 'pages/thank_you'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  self.per_page = 5
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(params[:comment].permit(:name, :body))

    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy

    redirect_to post_path(@post)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
    render :layout => false
  end

  def me
    render :layout => false
  end

  def contactMe
    render :layout => false
  end

  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    ActionMailer::Base.mail(:from => @email,
        :to => 'chavez.agustin@outlook.com',
        :subject => "A new contact form message from #{@name}",
        :body => @message).deliver_now
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 5)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(params[:post].permit(:title, :body))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to root_path
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= comment.name %></strong></p>
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> ago</p>
  </div>
    <% if user_signed_in? && current_user.admin? %>
      <p><%= link_to "Delete",[comment.post, comment],
                      method: :delete,
                      class: "button",
                      data: {confirm: "Are you sure?"} %>
      </p>
    <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :body %> <br>
    <%= f.text_area :body %>
  </p>
  <br>
  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>


  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main_content">
    <div id="header">
      <% if current_page?(posts_path) %>
        <p>All Posts</p>
      <% elsif current_page?(about_path) %>
        <p>Portfolio</p>
      <% else %>
        <%= link_to "Back to All Posts", posts_path %>
      <% end %>

      <% if user_signed_in? %>
        <div class="buttons">
          <button class="button"><%= link_to "Log Out", destroy_user_session_path, method: :delete %></button>
        </div>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
        <div class="buttons">
          <button class="button"><%= link_to "New Post", new_post_path %></button>
        </div>
      <% end %>
    </div>

    <div id="sidebar">
    <ul>
      <li class="category">Website</li>
      <li><%= link_to "Blog", posts_path %></li>
      <li><%= link_to "Portfolio", root_path %></li>
    </ul>

    <ul>
      <li class="category"> Social</li>
      <li><a href="https://github.com/agustinchavez">Github</li>
      <li><a href="#">Twitter</li>
      <li><%= link_to 'Email', root_path(:controller => "pages", :anchor => "get_in_touch") %></li>
    </ul>

  <% if !user_signed_in? %>
    <p class="sign_in"><%= link_to "Admin Login", new_user_session_path %><p>
  <% end %>
  </div>

    <% flash.each do |name, msg| %>
      <%= content_tag(:div, msg, class: "alert") %>
    <% end %>

    <%= yield %>
  </div>


</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Agustin Chavez</title>

   <!-- Custom styles for this template go here -->
   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Fredericka+the+Great' %>
   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Hind:300" rel="stylesheet' %>

   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Arbutus' %>


  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <%= stylesheet_link_tag    'styles', media: 'all', 'data-turbolinks-track' => true %>
    <!-- jQuery is required for Bootstrap to work -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.14.2/TweenMax.min.js"></script>
     <%= javascript_include_tag 'scripts', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- javscript API -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6_AGSzD00U-Y0cFt1NXFVF7GNo-yd39g"></script>

  </head>

  <body data-spy="scroll" data-target=".navbar"  >




<div class="container-fluid backContainer" style="width:100%;">
  <div class="row">
    <div class="col-md-12 bigBackground">
       <nav class="navbar  navbar-static-top" style="background-color: transparent;">
            <ul class="breadCrumbs">
              <li class="navLinks"><%= link_to "WORK", root_path %></li>
              <li class="navLinks"><%= link_to "ABOUT ME", me_path %></li>
              <li><img class="aclogo" src="/assets/ACLogo.png"><%= link_to "", root_path %></li>
              <li class="navLinks"><%= link_to "BLOG", posts_path %></li>
              <li class="navLinks"><%= link_to "CONTACT", contact_path %></li>
            </ul>
      </nav>
      <h1 class="splashHeader splashTitle">AGUSTIN</h1>
      <h1 class="splashSecond splashTitle">CHAVEZ</h1>
      <h4 class="splashHeader splashSub">WEB DEVELOPER</h4>
    </div>
  </div>
</div>

<div class="container-fluid" style="width:100%;">
  <div class="row">
    <div class="col-sm-3 box overlay firstBlock workRows">
      <p><a href="https://bikechicagodemo.herokuapp.com/" target='blank'>Bikes Chicago</a><p>
    </div>
    <div class="col-sm-6 box overlay secondBlock workRows">
      <p><a href="https://vast-eyrie-3700.herokuapp.com/" target="blank">Podcast Network</a><p>
    </div>
    <div class="col-sm-3 box overlay thirdBlock workRows">
      <p><a href="https://github.com/agustinchavez/teammatch" target="blank">TeamMatch</a><p>
    </div>
  </div>

   <div class="row">
    <div class="col-sm-7 fifthBlock ">
      <p>This portfolio belongs to me, Agustin Chavez, a developer, tv nerd, and overall swell guy, thanks for taking a look!<p>
    </div>
    <div class="col-sm-5 box overlay sixthBlock workRows">
      <p><a href="https://github.com/agustinchavez/tacotime" target="blank">TacoTime</a><p>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-2 box overlay seventhBlock workRows">
      <p><a href="https://github.com/agustinchavez/chicagosoccer" target="blank">ChicagoSoccer</a><p>
    </div>
    <div class="col-sm-6 box overlay eighthBlock workRows">
      <p><a href="https://codepen.io/agustinchavez/full/NRbABb/" target="blank">Simon Game</a><p>
    </div>
    <div class="col-sm-2 box overlay ninthBlock workRows">
      <p><a href="https://codepen.io/agustinchavez/full/bZJzVd/" target="blank">Tic Tac Toe</a><p>
    </div>
    <div class="col-sm-2 box overlay tenthBlock workRows">
      <p><a href="https://codepen.io/agustinchavez/full/GqEwGk/" target="blank">WikiViewer</a><p>
    </div>
  </div>
</div>

  <footer>
    <p class="footer_text"><a href="https://twitter.com/chavezagustin1" class="twitter-follow-button" data-show-count="false">@chavezagustin1</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></p>

    <ul class="footerList">
      <li><img class="aclogoFooter" src="/assets/ACLogo.png"></li>
      <li><a href="https://github.com/agustinchavez" target="_blank"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a></li>
      <li><a href="https://codepen.io/agustinchavez/" target="_blank"><i class="fa fa-codepen fa-2x" aria-hidden="true"></i></a></li>
      <li><a href="https://www.linkedin.com/in/agustin-chavez-479784b9" target="_blank"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a></li>
    </ul>
  </footer>


  </body>
</html>

app/views/pages/contactMe.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Agustin Chavez</title>

   <!-- Custom styles for this template go here -->
   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Fredericka+the+Great' %>
   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Hind:300" rel="stylesheet' %>

   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Arbutus' %>


  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <%= stylesheet_link_tag    'styles', media: 'all', 'data-turbolinks-track' => true %>
    <!-- jQuery is required for Bootstrap to work -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.14.2/TweenMax.min.js"></script>
     <%= javascript_include_tag 'scripts', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- javscript API -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6_AGSzD00U-Y0cFt1NXFVF7GNo-yd39g"></script>

  </head>

  <body data-spy="scroll" data-target=".navbar"  >


<div class="container-fluid" style="width:100%;">
  <div class="row">
    <div class="col-md-12">
       <nav class="navbar  navbar-static-top" style="background-color: transparent;">
            <ul class="breadCrumbs">
              <li class="navLinks aboutNav"><%= link_to "WORK", root_path %></li>
              <li class="navLinks aboutNav"><%= link_to "ABOUT ME", me_path %></li>
              <li><img class="aclogo" src="/assets/ACLogo.png"><%= link_to "", root_path %></li>
              <li class="navLinks aboutNav"><%= link_to "BLOG", posts_path %></li>
              <li class="navLinks aboutNav"><%= link_to "CONTACT", contact_path %></li>
            </ul>
      </nav>
    </div>
  </div>
</div>

<div class="container" id="contact_me">
    <div class="contact_me_pic">
      <h1 class="contact_me" id="get_in_touch">Get In Touch</h1>
      <div class="contact_information col-lg-4 col-md-4">
          <p>Interested in working together?</p>
          <br>
          <p>Send me an email with some information about your project.</p>
           <br>
          <p>Please allow up to a couple of business days for me to respond.</p>
      </div>

    <div class="contact-form col-lg-8 col-md-8">
      <%= flash[:notice] %>

      <%= form_tag("/pages/thank_you") do %>
      <div class="row">
        <div class="col-md-8">
          <div class="form-group" id="form-group-name">
            <%= label_tag :name, "Name" %>
            <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
          </div>
          <div class="form-group" id="form-group-email">
            <%= label_tag :email, "Email Address" %>
            <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
          </div>
          <div class="form-group" id="form-group-message">
            <%= label_tag :message, "Message" %>
            <%= text_area_tag :message, nil, :rows => 10, :cols => 20, class: "form-control", placeholder: "Enter Message" %>
          </div>
          <div class="submit">
            <button type="button" class="btn btn-primary">
              <%= submit_tag "Send" %><% end %>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <footer>
    <p class="footer_text"><a href="https://twitter.com/chavezagustin1" class="twitter-follow-button" data-show-count="false">@chavezagustin1</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></p>

    <ul class="footerList">
      <li><img class="aclogoFooter" src="/assets/ACLogo.png"></li>
      <li><a href="https://github.com/agustinchavez" target="_blank"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a></li>
      <li><a href="https://codepen.io/agustinchavez/" target="_blank"><i class="fa fa-codepen fa-2x" aria-hidden="true"></i></a></li>
      <li><a href="https://www.linkedin.com/in/agustin-chavez-479784b9" target="_blank"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a></li>
    </ul>
  </footer>

</body>
</html>

app/views/pages/me.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">

    <title>About Me</title>

   <!-- Custom styles for this template go here -->
   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Fredericka+the+Great' %>
   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Hind:300" rel="stylesheet' %>

   <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Arbutus' %>






  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
    <%= stylesheet_link_tag    'styles', media: 'all', 'data-turbolinks-track' => true %>
    <!-- jQuery is required for Bootstrap to work -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://code.jquery.com/jquery-latest.min.js"></script>
    <!-- Latest compiled and minified Bootstrap JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/gsap/1.14.2/TweenMax.min.js"></script>
     <%= javascript_include_tag 'scripts', 'data-turbolinks-track' => true %>
     <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

    <!-- javscript API -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD6_AGSzD00U-Y0cFt1NXFVF7GNo-yd39g"></script>

  </head>

  <body data-spy="scroll" data-target=".navbar"  >

  <div class="container-fluid">
  <div class="row">
    <nav class="navbar  navbar-static-top" style="background-color: transparent;">
            <ul class="breadCrumbs">
              <li class="navLinks aboutNav"><%= link_to "WORK", root_path %></li>
              <li class="navLinks aboutNav"><%= link_to "ABOUT ME", me_path %></li>
              <li><img class="aclogo" src="/assets/ACLogo.png"><%= link_to "", root_path %></li>
              <li class="navLinks aboutNav"><%= link_to "BLOG", posts_path %></li>
              <li class="navLinks aboutNav"><%= link_to "CONTACT", contact_path %></li>
            </ul>
      </nav>
    <div class="col-md-12 aboutSplash">
      <h1>AGUSTIN CHAVEZ</h1>
      <h3>Web Developer</h3>
      <p class="meBlurb">
        - Hi Friends, this portfolio belongs to me, Agustin Chavez,<br> a self-taught Developer, soccer lover, food fanatic, music enthusiast, and so much more.
      </p>
    </div>
  </div>
  </div>
    <hr style='border: none; clear: both'>

    <div class="container-fluid aboutSubSect">
  <div class="row">
    <div class="col-md-4">
      <h4 class="aboutMeTitle">ABOUT ME</h4>
      <p>Oh good, I get to talk about myself some more! I didn't take the traditional route into web development, I studied Political Science at the University of Illinois at Urbana-Champaign, and then spent a couple of years in law school. As a Web Developer, I enjoy working on projects that are cool, innovative, and provide solutions to real people. I play soccer (I love sports!) and I love to interact with the Futbol community. I really appreciate you taking the time to look at my work, if you think we'd be a good match, I'd love to work on a project with you.</p>
    </div>
    <div class="col-md-4">
    <h4 class="aboutMeTitle">TECHNOLOGIES I WORK WITH</h4>
      <p>I've had the pleasure to work with a variety of technologies. Ruby and Ruby on Rails are my main squeeze right now, but i've also worked with Node, and RubyMotion.I am currently plying my trade as a .NET Developer, working with C# on the ASP.NET framework. I am fluent in front end technologies, and make mobile first development a priority. JavaScript, JQuery, HTML, CSS, Sass, and Bootstrap are a few of the tools in my repertoire.</p>
    </div>
  </div>
  </div>

<footer>
    <p class="footer_text"><a href="https://twitter.com/chavezagustin1" class="twitter-follow-button" data-show-count="false">@chavezagustin1</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script></p>

    <ul class="footerList">
      <li><img class="aclogoFooter" src="/assets/ACLogo.png"></li>
      <li><a href="https://github.com/agustinchavez" target="_blank"><i class="fa fa-github fa-2x" aria-hidden="true"></i></a></li>
      <li><a href="https://codepen.io/agustinchavez/" target="_blank"><i class="fa fa-codepen fa-2x" aria-hidden="true"></i></a></li>
      <li><a href="https://www.linkedin.com/in/agustin-chavez-479784b9" target="_blank"><i class="fa fa-linkedin-square fa-2x" aria-hidden="true"></i></a></li>
    </ul>
  </footer>

  </body>
</html>

app/views/pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. I have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
<% if @post.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
    <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper"
  <h1>Edit post</h1>

  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <div class="post_wrapper">
   <h2 class="title"> <%= link_to post.title, post %></h2>
   <p class="date"> <%= post.created_at.strftime("%B, %d, %Y") %></p>
  </div>
<% end %>

<%= will_paginate @posts %>

app/views/posts/new.html.erb
<div id="page_wrapper"
  <h1>New post</h1>
  <%= form_for :post, url: posts_path do |f| %>
    <% if @post.errors.any? %>
      <div id="errors">
        <h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving</h2>
        <ul>
          <% @post.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <p>
      <%= f.label :title %><br>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>

    <p>
    <%= f.submit %>
    </p>
  <% end %>
</div>

app/views/posts/show.html.erb
<div id="post_content">
  <h1 class="title">
  <%= @post.title %>
  </h1>

  <p class="date">
    Submitted <%= time_ago_in_words(@post.created_at) %> ago.
    <% if user_signed_in? %>
      | <%= link_to "Edit", edit_post_path(@post) %>
      | <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" } %>
    <% end %>
  </p>

  <p class="body">
    <%= @post.body%>
  </p>

  <div id="comments">
    <h2><%= @post.comments.count %> Comments</h2>
    <%= render @post.comments %>

    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>
</div>